### ISSUE TITLE
 r.Update(context.Background(), instance) throws exception for newly submitted job 

### ISSUE THREAD

**Issue by Azadehkhojandi** [microsoft/azure-databricks-operator#40] opened 2019-06-26 01:23 UTC
Reconciler error    {"controller": "notebookjob", "request": "default/sample1run16", "error": "error when refreshing job to API: error when updating NotebookJob: Operation cannot be fulfilled on notebookjobs.databricks.microsoft.com \"sample1run16\": the object has been modified; please apply your changes to the latest version and try again"}

**Comment by xinsnake** [comment] 2019-07-23 01:46
This seems to be caused by not pulling the latest status when doing the update. This is currently fixed in the new models.

**Closed by xinsnake** 2019-07-23 01:46 UTC
